#!/bin/bash

base_port=60000

# E.g. 1.1.1.1
server_ip=$1
shift

# E.g. 5
num_clients=$1
shift

# E.g. 60
test_duration=$1
shift

# E.g. report
report_base=$1
shift

# E.g. -u -b 10M
iperf_options="$*"

# Run iperf multiple times
for i in `seq 1 $num_clients`; do

	# Set server port
	server_port1=$(($base_port+$i));
	# Report file includes server ip, server port and test duration
	report_file1=${report_base}-${server_ip}-${server_port1}-${test_duration}-bbr.txt

	# Run iperf
	iperf3 -c $server_ip -p $server_port1 -t $test_duration -C bbr -P 50 &>$report_file1 &
done
